maintainer: Drew Linsley
version: 0.1  # Version of the config and data generation

##
ca2_data:
  raw_videos: /Users/drewlinsley/Documents/valo_share/Valo/Valo-Operant_Collaboration - Documents/Pilot_calcium_imaging_data  # Folder for raw videos
  fps: 24  # Display frames per second for saving example videos
  processed_videos: /Users/drewlinsley/Documents/proc_ca2_vids  # Folder for saving processed videos
  processed_npys: /Users/drewlinsley/Documents/proc_ca2_npys  # Folder for saving processed numpy arrays

segmentation_model:
  ckpt: ckpts/seg3d_epoch_216.pth  # Segmentation model checkpoint
  segments: nucleus_segments  # Folder for saving nucleus segments in numpy

tracking:
  fast_process: true  # Use fast non-interactive matplotlib backend

  # Data gen settings
  generate_rois: true  # Generate single-cell videos and stats 
  save_npy_rois: true  # Save ROI videos as .npy files

  # Hyperparameters
  small_vol_thresh: 150  # Ignore segmented nuclei smaller than this in pixels
  dilation_radius: 3  # Near cytoplasm width
  dilation_radius_far: 9  # Far cytoplasm width
  roi_size: 48  # Single-cell video size in pixels
  tracking_strategy: first  # {first, all} Track by the first frame or all frames (all is slower but more accurate)
  detrend_mean_nucleus: false  # Detrend based on mean nuclear signal
  linear_detrended: false  # Detrend based on global mean
  use_dff: true  # Transform activity by computing df/f
  normalize_rois: false  # Normalize each single-cell ROI to [0, 1]

  # Visualization settings
  debug: false  # Generate plots and videos along the way
  plot_trended_video: false  # Plot the original videos
  plot_detrended_video: false  # Only used if linear_detrended or detrend_mean_nucleus is true
  plot_figures: true  # Generate per-cell figures parameter fit figures

sparks:
  # Paths
  ckpt: ckpts/epoch_122.pth
  control_plot: control.png
  drug_screen_plot: drug_screen.png
  drug_screen_normalized_plot: drug_screen_normalized.png
  model_type: cytoplasm_far_split_rois  # Cell region you want to analyze
  nmf_file: nmf_model.joblib  # NMF decomposition model path
  pls_file: pls_model.joblib  # PLS decomposition model path
  regenerate_nmf: true
  omni_csv_output_path: mean_cell_analysis.csv
  event_csv_output_path: all_spark_analysis.csv
  spark_classifier_file: spark_classifier_file.npz  # Build a dataset for training a spark detection model

  # Settings
  te_bs: 32  # Batch size for spark analysis
  test_workers: 16  # Number of threads for data loading
  plot_videos: true  # Generate annotated videos for each cell. Slow!
